
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgCf9e7e0yvaz9DNWUv05Qmmn+mDZdGmjpvG+KTS5QEzinyBsoK4NoRVN6Q1oRSn7SCTNYRd+XRiL7sUIYul7U/muxzFbbbLc/5A2XAQ6HXU5Clw/3RG1NrBHGmL+TwmHTaTW/26DRLsBmelcLw/bU4A+X5n3ahteAmkQUYBJ6jpZ+wHuhByzBCkS/HJBUaNpbJ2IK1DIHHqibyuxjXr4q5GoQLiI0ieAFaJz9JUo5v6nIUoShfIwIevauEGBmagSOjpSvcMSDceaWUHH62p26Ma0mRBZ1pbExecrgjjAZkyCG1oK0Sma0ljS+PiiGpHqfXtn0jfgFwaM4JDBugetIgrCnqOtMKlUT7FrK0xmci2rhV4DG8NkiUHeIQnCna6TyHGUTnhewoj9wkVFXj/xBOPhjphY8b+Ze3Rp2zcNYy3PVsQo2uV6jfLpeASsGJhI8FVe0VGviJM5eJbKZOla576TT9DBOEv+zSkGTrHYCLNDMWXXAR5ixG6nCX3J/HaL7Vnw8T0Xc6sOHBOdcBjyI44hVAtYufJE5hSaK0fLt6w/fogSiX0LEr4OWLGzQBUQFdP1GFdyVa/HHbY0N0A6kwshf4vIpxE1ufZmiJGt2hRkMzO8OEwQk9xzoJEOARt8pxkUPhaXyw0d2ByfRbDErfb3jHFeQJJmjd5qHGwqo8oMctLdBrchh4UKKL8vTVaSRU=
    user: AgC5kaQGqOOG2DCU9dHXaV8rp8/bUD3vBqKbw/4o0atZXJ0zSjTzCIJ5GGiCQYDb7aIXsmEkCDmkWKoRnOgVNP8jMSlPjzLtO6NLn6CgB+X4R+T7Iahc+lYMvpfymyYyWQ2WiBXa+3q4Ugdce0DxwKr9gInLjGtKvJ/Uwb2/T7PJ9ZSj4ZMN0HIffWTbmwDXxE3mKRG7XnBwdDjesdKYd4ELLw82CZ8juYA3FRLxUAiepR0xL+QVpFAfEH36735v0cSFkJ68rcsiSrlid3CGcxHCkHqBweJgOPTvivSUmxAUlw+xwKiCqN0ezWEhLxIsjrDJt1xs+dn7RcZQmom31Gc5J1du5FEoQfN3gtYZxxV63CxF/W7PG0olxbpgEro4NI9ETLUiUwXDvvwkuWoDnfbb17E+tDOKOxsbdMhM6Gy8TZ3MlkPDGb/nPR8Vb+kSkZI5o3OiuuIsEU3OgY9OtdzlsAK/MN/QsgXux00x1xenrpEgbxrTofOQ7Jrp1jSgr+JIAEP3VQ2nkN7STh5oFRVFzSjayhZ0W/yaocRAOVDKkAO2t5xF5FP/okusb3ZdCxGOR2JptEHzL7mzZon1oiYvZHnp7ja0QERt1SbTmb86GIJ0PDoqEwJ4d73HjPPGZV9UqqnrVytSVTBuzGxlMJhJmP4EQeetqy5RQEdocflU/2+CWwe4IucVrcccTXRuDqM7i2AeVB1ZDQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
